### ISSUE TITLE
One record marked as "invalid" but the original CMDI file validates under xmllint

### ISSUE THREAD

**Issue by jknappen** [clarin-eric/curation-dashboard#129]
Checking the curation dashboard today, it marks one of our CMDI files as invalid, but I can't make sense of the error message. The CMDI file in question validates under local validation using xmllint.

The file is on this webpage:

https://curation.clarin.eu/collection/UdS_CLARIN_D_Repository.html

And the error messages read:

    line: 30, col: 49 - cvc-complex-type.3.2.2: Attribute 'debug-outer-false' is not allowed to appear in element 'cmdp:contributor'.
    line: 31, col: 49 - cvc-complex-type.3.2.2: Attribute 'debug-outer-false' is not allowed to appear in element 'cmdp:contributor'.
    line: 32, col: 49 - cvc-complex-type.3.2.2: Attribute 'debug-outer-false' is not allowed to appear in element 'cmdp:contributor'.

I cross-checked with the closed issue #31 but in this case the error message is a different one.

**Comment by wowasa** [comment]
I checked the schema: curation is right, since the attribute 'debug-outer-false' is not allowed in element 'cmdp:contributor'. Means your tool doesn't validate correctly. But if you use an online tool like [W3C XML Schema (XSD) Validation online](https://www.utilities-online.info), you will receive the same error report. 
All you have to do is to delete the attribute 'debug-outer-false' from lines 30-35

**Comment by wowasa** [comment]
p.s.: I'm wondering why the linkchecker has qualified the fedora link from the file as undetermined - but I'm checking this anyway in the next couple of days

**Comment by jknappen** [comment]
Thanks! I fixed the CMDI file in question.
