### ISSUE TITLE
Provide a link from Collection report to VLO with corresponding collection-filter

### ISSUE THREAD

**Issue by vronk** [clarin-eric/curation-dashboard#13]
To be able to explore the instance data of given collection for further inspection, it would be nice to have a link in the collection report pointing to the appropriate query in the VLO. 
(However not sure if there is a reliable matching on any vlo-facet - first candidate would be the vlo:collection facet)

**Comment by wowasa** [comment]
as far as I can see this issue requires a different grouping in curation: 
in curation collections are grouped by directory name which corresponds to the data provider while a collection in vlo terms is taken from the MdCollectionDisplayName element of the cmd file. 
Since one data provider might provide the data for more than one collection, we must clearly define first what we want: we could either regroup curation collections in the terms of vlo collections and provide a corresponding link from curation to vlo. 
Or we have to investigate for each curation collection the corresponding vlo collections first and then either display them with one-to-one links or a one-n link from curation-collection to vlo-collection, which might require a quite large filter with or joins. 
No big deal but we should discuss what we want exactly and if the confusion for the user isn't bigger than the benefit. 
I'm shifting the issue to milestone 5.4, since we have to discuss it first

**Comment by twagoo** [comment]
Alternatively we could add an index to the VLO for source directory, which could then be exploited by the curation dashboard based on already available information.

**Comment by wowasa** [comment]
we should either tackle the issue now or close it

**Comment by twagoo** [comment]
Note my comment in  https://github.com/clarin-eric/VLO/issues/375 that an alpha implementation of this feature could already be achieved by using a pattern based on the following example:

`https://vlo.clarin.eu/search?q=_fileName:*clarin/results/cmdi/HZSK_Repository*`

**Comment by wowasa** [comment]
implemented in v. 6.3.0
