### ISSUE TITLE
Show indication of omitted rows in truncated link checking status tables

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/curation-dashboard#157]
At https://curation.clarin.eu/linkchecker/Overall (and other places?) incomplete tables are rendered. If I'm not mistaken, these tables are 'previews' whereas the full data are available via the download links. However the fact that these tables are truncated representations of larger data sets is not very clearly indicated. I suggest putting an approximation of the number of rows not displayed (based on the total number known at the time of generation) so as to give the user an idea of the 'size' of each category rather than an impression of complete data that the casual visitor might get from this.

**Comment by wowasa** [comment]
We need to discuss on our next meeting what we exactly want here. At the moment we use in the static view an SQL query which returns the latest n status of each category for a specific providergroup or overall. If we wan't to have the total result somewhere (which indeed we said already that we want it), we have the challenge again that we need to query for count and latest status at the same time. Since the linkchecker keeps on turning in the background, the result might have changed otherwise. 
So my suggestion is not just to create a static preview with some n status for each category but to make the downloadable XML static and to generate the other formats from it by XSLT. But this would on the other hand mean to create three times a week some really large XML files

**Comment by twagoo** [comment]
From the minutes:

> we do not try to align/synchronise all counts but we make sure that there is a clear indication of the fact that the table is truncated and that the number of items in the download may be different
acknowledge asynchronous nature rather than ‘solving’ it :)

**Comment by wowasa** [comment]
implemented in v. 6.1.0
