### ISSUE TITLE
Assure faster cache initialization

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/curation-dashboard#224]
related to issue #223 

Caches that require external information might take a quite long time to be filled. In case of the concept cache where, after the latest change in the API, we have to fire a request for each concept, filling the cache might lead to a timeout. 

Hence we have to assure that those caches that fire numerous requests are either initialized before user interaction or make the initialization process faster by persisting the data locally between two starts of the program. 

Hence I see three options: 
1. a pre-initialization of the cache at start-up
In case of the concept registry we had to load the most popular concept definitions
2. an additional file cache for single information
We're doing so already for schema, where we store each schema in the file system. To fill the cache we look up the schema at first locally and download it, if it's not there
3. serializing and persisting the cache himself

**Comment by wowasa** [comment]
Twan's suggestion is to have a look at https://jankotek.gitbooks.io/mapdb/content/htreemap/

Conditions for usage are: 

1. cache persistence between multiple runs of curation (app and web)
2. Spring compliance
3. Expiration/persistence must be configurable for a specific cache

**Comment by wowasa** [comment]
MapDB is no standard solution for Spring and resolves an issue we don't have, since the issue is not the cache itself but persistence and expiration of specific caches. To integrate MapDB properly in Spring Boot we have to code a specific CacheManager, which handles creation of named caches, persistence and expiration as well as a Cache implementation.   
Therefore I decided to use a simple file cache in the same way we're doing for schema: we look up the file from the cache directory, download it there, if it doesn't exist and process the locally stored file then. Since the file cache is not persisted outside the container, the file cache is renewed after each start of the container.

**Comment by wowasa** [comment]
done

**Comment by twagoo** [comment]
I'm glad that there is a solution for this now and functionally it sounds like it does the job! However looking at https://github.com/clarin-eric/curation-dashboard/blob/18a0391f571e051aebdd5f34b85871b79be24dbb/curation-ccr/src/main/java/eu/clarin/cmdi/curation/ccr/cache/CCRCache.java I don't think this should be the final state of the code. Since we are crafting our own solution here, the code needs to be refactored for readability (150+ lines is too much for a method), documented and covered by tests IMO. Maybe this is still in an open todo, in which case ignore my comment.
