### ISSUE TITLE
Reduce calls to actual services in tests

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/curation-dashboard#244]
When running all tests in curation-dashboard, a large number of requests to live services are made. This has a number of downsides:
- tests depend on service availability and specific content
- it slows down the tests
- it causes a load on the services

Suggestion: replace the live services with mocks.

**Comment by wowasa** [comment]
see #234

**Comment by wowasa** [comment]
reopening issue since I prefer a different treatment for the tests for data processing than for testing http calls and responses, that were initially the goal of issue #234. Testing data processing requires too many expectations for mockserver, since we have to create an expectation for any concept and profile. Therefore I prefer to copy concept definitions, profiles and public profile headers into a file cache for testing (later the persistence layer of our cache manager) and to use the mockserver only for testing http calls and responses in services

**Comment by wowasa** [comment]
implemented in java21 branch
